import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import { selectFeed } from '../feed/FeedSlice';
import { useSelector } from 'react-redux';

//Fetching and updating state with comment arrays...
///Access the state array of feed posts - THIS IS IMPORTANT - needs to be performed at this level so that each post can be iterated on rather than just the comments within a post
///map through the array, first constructing a link for each loop to access comments
///for each loop, push the comments to the object in commentsByPost that match the id of the post

//New plan - come up with a way to dispatch the action only when someone clicks each post to expose the comments instead of adding all comments to state on the initial page load
/*
New process:
1. ***Will this cause an undesired re-render??*** In each feedTile, include an attribute that is the constructed url to each post ('reddit.com/${permalink}${dotJson})
2. Write an onClick event handler that follows a process something like:
    1. dispatch an action that fetches the .json url for that particular post (the url containing comment info).
        This action will take the .json url as the argument
    2. The corresponding extraReducer will take the returned value (the json page of comments) and push all the top level
        comments into the commentsByPost.comments array
    3. The event handler will then populate a corresponding component or JSX with the comment info just added to state
    4. The event handler will then change the css display value from none to block?
    5. Will need to add conditional logic that doesn't run the event handler in the case that state already exists for 
        comments for that post? First, see what performance is like to not add this. Functionally it could be better to
        be able to fetch new comments without refreshing the page.
*/
//const feedPosts = useSelector(selectFeed);
const constructCommentUrl = (postDetails) => {
    const postUrlExtension = postDetails.data.permalink;
    
    const baseUrl = 'reddit.com';
    const dotJson = '.json';

    const jsonUrl = baseUrl + postUrlExtension + dotJson;

    return jsonUrl;
}

export const fetchComments = createAsyncThunk(
    'comments/fetchComments',
    async (commentsByPostState) => {
        commentsByPostState.map((post) => {

        })
        
        const response = await fetch(commentUrl);
        const json = response.json();
        const commentsObjectsToLoop = json[1].data.children //This produces an array. The comment values of each element in the
        //array can be accessed by commentsObjectsToLoop.data.body
        return commentsObjectsToLoop;
    }
)

const commentsSlice = createSlice({
    name: 'comments',
    initialState: {
        commentsByPost: [],
        isLoading: false,
        hasError: false
    },
    reducers: {
        addPostUrls: (state, action) => { //I want this to create objects in the commentsByPost state valuewhich will contain
            //the url for each post loaded in the initial post state (***which will be the payload here for this action creator***)
            //Then I will need to have an async thunk(?) that fetches comments on each post and updates the commentsByPost state???
            action.payload.map(post => {
                
                const baseUrl = 'reddit.com';
                const postUrl = post.data.permalink;
                const dotJson = '.json';
                const jsonUrl = baseUrl + postUrl + dotJson;

                state.commentsByPost.push({[post.data.id]: {url: jsonUrl, comments: []}});
                //state.commentsByPost = action.payload;
            })
        },
        addCommentsForEachPost: (state, action) => {
            state.commentsByPost.comments = action.payload;
        }
    },
    extraReducers: (builder) => {
        builder.addCase('fetchComments.pending', (state) => {
            state.isLoading = true;
            state.hasError = false
        })
        .addCase('fetchComments.fulfilled', (state, action) => {
            //need to iterate over the array generated by the payload and update commentsByPost accordingly
            //action.payload.map(())
            state.isLoading = false;
            state.hasError = false;
        })
        .addCase('fetchComments.rejected', (state) => {
            state.isLoading = false;
            state.hasError = true;
        })
    }
})
//})

export const { addPostUrls, addCommentsForEachPost } = commentsSlice.actions; //Not sure if this is correct, haven't checked against Codecad lesson

export const selectCommentsByPost = (state) => state.comments.commentsByPost;

export const selectIsLoading = (state) => state.comments.isLoading;

export const selectHasError = (state) => state.comments.hasError;

export default commentsSlice.reducer;